name: Blogv1
favicon: null
layout_spectrum: 0.70501
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6050780126824975
  lightness: 0.6088956135790795
  saturation: 0.3940066038630903
  rhythmicContrast: 0.9368967721238732
purpose: []
